### ISSUE TITLE
Waste of the 0th row and column

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/ChemLab#3]
# Index '0'

Current implementation of `chemlab.core.chemical.BalanceSolver` frequently uses arrays in a such way when the first row and column (with index '0') are simply never used.
The `fData` private member uses the first column as a "key" -- it's an identifier of element. And that's all. The member functions (as a rule) internally use `1` as index of the "first" row/column.

In places where it's possible that must be fixed **with switch to `0` as an index of the first row/column** as the current implementation wastes memory resource.

I can't assign the ticket to anyone but it's mine (@ruslangaripov).
Tags: #BalanceSolver #index0 #array #improvement #implementationdetails

**Comment by ruslangaripov** [comment]
Closed as I moved the ticket to my own branch.

**Comment by Serg-Norseman** [comment]
You've got a job, I look in full swing :) I just came to see what's going on here... how many messages!
:)
