### ISSUE TITLE
Move loop invariants out of loops (while finding matrix inversion)

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/ChemLab#4]
# Description

There are many **nested** for-loops executing when `BalanceSolver` is determining a matrix of cofactors. We have a chance to reorder structure of the loops tree and gain some performance.
## Current state

When the `chemlab.core.chemical.BalanceSolver.inversion` method calculates a matrix of cofactors it uses the following algorithm:
1. The method runs two nested for-loops (one for rows and another one for columns of a source matrix). Therefore we get iterations for each entry of the matrix.
2. For each entry the method calculates a matrix cofactor (in transpose matrix) using the Leibniz formula to find determinants:
- Initializes permutation sequence,
- Cycles through all possible permutations,
- Calculates a determinant.
## Proposal

There are heavy calculations in the second step (cycle **over all permutations** of the sequence **for each entry in the source matrix** (number of possible permutations is factorial of the sequence length!) and finding a next possible permutation). I propose to move the second step to the top and to make it the first one:
1. Initialize permutation sequence,
2. Cycle through all possible permutations (this is `for` statement with {_length_}! iterations number),
3. Cycle over all entries in the source matrix and calculates a part of a minor,
4. At the end of all iterations over all possible permutations we get the transpose matrix of cofactors.

Assigned to me (@ruslangaripov).
Tags: #BalanceSolver #improvement #implementationdetails

**Comment by ruslangaripov** [comment]
Close as I moved the ticket to my own branch.

**Comment by Serg-Norseman** [comment]
Powerful!

**Comment by ruslangaripov** [comment]
No :smile: I couldn't did anything with that! See ticket #18 in my repository.
